### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by Modem68** [andgly95/Tailored-Nutrition#54]
**What Works?**
- UI
- Basic functionality of bar code scanner
- API Querying 
- Sign-up/Sign-in Logic Progression
- Basic Search Screen

**Solved Challenges**
- Choice of database to use to store user information (SQLite)
- Choice of database to extract nutrition info from (NutritionX)
- Querying the API
- Created more pages than just the sign-up and sign-in pages
- Combining both sets up sign-up pages

**Unsolved Challenges**
- Extracting the desired macros from NutritionX
- Setting up the user profile page
- Creating proper flow for authentication
- Creating icon for user profile page
- Fix up any minor odds and ends which make the app look unattractive

**Comment by Codeofsanju** [comment]
I will spend some time tomorrow creating a pdf?
 -> Are we supposed to have one?

**Comment by Modem68** [comment]
I thought we need a powerpoint presentation.

**Comment by Codeofsanju** [comment]
working on the slide show

**Comment by Modem68** [comment]
Got it.

**Comment by Codeofsanju** [comment]
Done!
