### ISSUE TITLE
User Account (db side) / user profile (ui side)

### ISSUE THREAD

**Issue by Codeofsanju** [andgly95/Tailored-Nutrition#59]
**Questions** @HashedTag 
1. Is not being able to create more than one account per phone by design?
      -> if not, there seems to be a bug where you cannot
2. How do I delete an account I made so can test making another one?

**Implementations** 
1. Passing Name to userProfile 
2. @andgly95 barcodescanner does not seem to work in our search tab of userprofile, please help with this.
3. keyboard blocking view seems to be a universal problem throughout the UI, someone please fix this.

**If anyone has issues with node modules**
1. Try npm install
2. If this does not work, you may want to delete node module folder and then npm install again (known react native bug, advice right from facebook)

**Quick Suggestions**
1. If anyone has trouble making an account and signing in with it to view the userProfile I have created, simply make userProfile initialRouteName in App.js

# **Good Job Everybody!!!**

**Comment by LambdaCall** [comment]
You should be able to make as many accounts as you want, whats the bug?
Also you can't delete accounts since i havn't finished implementing sessions yet...

**Comment by Codeofsanju** [comment]
Seems like when I try to make another account it simply says failed, a count was not created hmm

**Comment by Codeofsanju** [comment]
Pretty much everything here is acknowledged except keyboard blocking view and the barcodescanner no longer working now that search is part of userProfile. (search.js is now post.js in the Profile folder, work off that!!!)
