### ISSUE TITLE
Keyboard blocking view

### ISSUE THREAD

**Issue by Codeofsanju** [andgly95/Tailored-Nutrition#62]
Our presentation is tomorrow so I will not be playing with what we have so far today. I will fix this issue shortly after!

**Comment by Modem68** [comment]
@Codeofsanju I tried everything that supposedly fixes the issue and nothing works. Pushed a "solution" to my branch so e could potentially work on it Friday.

**Comment by LambdaCall** [comment]
Modified form so that keyboard inputs are at top instead of the bottom.
